#!/bin/bash
# WS Film — cover footage: turntable a VibeCAD cover's box.glb into the film-ready
# library at footage/<slug>/ (transparent PNGs + sheet.png + sheet.json — the exact
# format the compositions consume; the film never plays <video>), plus a small
# dark-background preview.mp4 for human checking on the ops panel only.
#
#   gen_footage.sh <cover.json> [frames=240] [size=900]
#
# GLB source: the NEWEST showcase variant (variants.json[0] on the hotsite) — that
# is the box the operator sees and approves on agents.wssoltech.au. out/<slug>/box.glb
# is only a fallback: every build overwrites it, so a stray build (the round-6/7 mock)
# leaves it carrying art that no longer matches the page. Variants archive box-lite.glb,
# which is what the showcase viewer renders — footage matches the page by construction.
set -euo pipefail
CFG="${1:?usage: gen_footage.sh <cover.json> [frames] [size]}"
FRAMES="${2:-240}"   # 240 = on-ones smoothness for an 8 s film scene (1.5°/frame)
SIZE="${3:-900}"
DIR="$(cd "$(dirname "$0")" && pwd)"

SLUG=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['slug'])" "$CFG")
GLB=$(python3 - "$SLUG" <<'PY'
import json, os, sys
slug = sys.argv[1]
vdir = f"/var/www/ws-agents-hotsite/vibecad/{slug}"
man = f"{vdir}/variants.json"
if os.path.exists(man):
    for v in json.load(open(man)):          # newest first — what the page shows
        p = f"{vdir}/{v['id']}/box-lite.glb"
        if os.path.exists(p):
            print(p)
            sys.exit(0)
fallback = f"/root/ws-vibecad/out/{slug}/box.glb"
print(fallback if os.path.exists(fallback) else "")
PY
)
if [ -z "$GLB" ] || [ ! -f "$GLB" ]; then
  echo "ERROR: no GLB found for $SLUG — publish the cover first (VibeCAD trigger)" >&2
  exit 1
fi

OUT="$DIR/footage/$SLUG"
echo "==> turntable: $GLB -> $OUT ($FRAMES frames @ ${SIZE}px)"
node "$DIR/turntable.js" "$GLB" "$OUT" "$FRAMES" "$SIZE"

echo "==> preview.mp4 (human conference only — the film consumes the PNG library)"
ffmpeg -y -hide_banner -loglevel error \
  -f lavfi -i "color=c=0x14141a:s=${SIZE}x${SIZE}:r=24" \
  -framerate 24 -i "$OUT/f%03d.png" \
  -filter_complex "[0][1]overlay=shortest=1,scale=480:-2,format=yuv420p" \
  -movflags +faststart "$OUT/preview.mp4"

# stamp provenance into sheet.json so the panel (and future sessions) can tell
# WHICH glb produced this footage
python3 - "$OUT/sheet.json" "$GLB" <<'PY'
import hashlib, json, os, sys, datetime
sheet, glb = sys.argv[1], sys.argv[2]
d = json.load(open(sheet))
d["source_glb"] = glb
d["glb_md5"] = hashlib.md5(open(glb, "rb").read()).hexdigest()
d["glb_mtime"] = datetime.datetime.fromtimestamp(os.stat(glb).st_mtime,
                                                 datetime.timezone.utc).isoformat(timespec="seconds")
d["generated"] = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
open(sheet, "w").write(json.dumps(d, indent=1) + "\n")
# sheet.js sidecar: compositions read the frame geometry through a plain <script>
# include, which works over file:// (render path) where fetch() of the json would not
slug = os.path.basename(os.path.dirname(sheet))
open(os.path.join(os.path.dirname(sheet), "sheet.js"), "w").write(
    "/* GENERATED by gen_footage.sh — do not edit */\n"
    "window.FOOTAGE=window.FOOTAGE||{};"
    f"window.FOOTAGE[{json.dumps(slug)}]={json.dumps(d)};\n")
PY

echo "==> done: $OUT ($(ls "$OUT"/f*.png | wc -l) PNGs + sheet.png + sheet.json + preview.mp4)"
